name: Create Sample Release

on: push

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        shell: bash
        run: |
          release_name=Calling-TUtorial
          unset CI
          # Build everything
          npm run setup
          npm run build
          npm run package

          7z a -tzip -r "calling-tutorial-build.zip" ./Client/dist/*

          # Delete output directory
          rm -r "./Client/dist"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "calling-tutorial-build.zip"
          tag_name: Newest Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}